@startuml
title Typical Command Sequence Diagram

actor User
participant ":Ui" as Ui
participant ":MediStock" as App
participant ":Parser" as Parser
participant ":Command" as Command
participant ":Inventory" as Inventory
participant ":Storage" as Storage
participant ":HistoryStorage" as HistoryStorage

User -> Ui : enter command
Ui -> App : input
activate App

App -> Parser : parseCommand(input)
activate Parser
Parser --> App : command
deactivate Parser

App -> Command : execute command
activate Command

Command -> Inventory : read / modify data
Inventory --> Command : result

Command -> Ui : show result / error


Command --> App : return
deactivate Command

App -> Storage : saveToFile(inventory)
Storage --> App : success

App -> HistoryStorage : save(histories)
HistoryStorage --> App : success

App --> Ui : continue loop / exit
deactivate App
@enduml